### ISSUE TITLE
[Bug] Kinoko Nasu breaks the game!

### ISSUE THREAD

**Issue by Sakimotor** [requinDr/tsukihime-port#19]
Had this funny CSS moment when the credits began so I took a screenshot and saved a slot when they started
![firefox_ioOi7j8odi](https://github.com/requinDr/tsukihime-port/assets/20578016/a2314149-cbf6-4f3d-8c62-e3cdfc71bb35)

now opening "New", "Continue" or "Load" just breaks the window and leaves the background alone
![cvjbk5aqSh](https://github.com/requinDr/tsukihime-port/assets/20578016/0cbdfbe0-dfda-430a-8c15-d22a975257da)

Pasting my exported saves just incase
[2023-10-04_00-48.zip](https://github.com/requinDr/tsukihime-port/files/12797461/2023-10-04_00-48.zip)

**Comment by popcornic420** [comment]
I too encountered this issue, particularly after my first ending with Arcueid. Initially reported this via the Google Form provided in the website but I saw this issue opened and thought I can also share.
[2023-10-04_00-21.thfull.zip](https://github.com/requinDr/tsukihime-port/files/12837622/2023-10-04_00-21.thfull.zip)

**Comment by loicfrance** [comment]
It should be fixed in the current release (sorry for the lack of update on this issue).
However, A savestate created at this point on the previous release can make the page crash when going to the "Load" screen or starting the game.
If you have a savestate at this point, I suggest that you export the `.thfull` file, edit it (it's a json file) to remove the savestate and load it back into the game.
Please tell us if you still face this issue on the current release. If you don't, I'll close the issue.

**Comment by Sakimotor** [comment]
> It should be fixed in the current release (sorry for the lack of update on this issue). However, A savestate created at this point on the previous release can make the page crash when going to the "Load" screen or starting the game. If you have a savestate at this point, I suggest that you export the `.thfull` file, edit it (it's a json file) to remove the savestate and load it back into the game. Please tell us if you still face this issue on the current release. If you don't, I'll close the issue.

Seems fine to me!

**Comment by popcornic420** [comment]
Works okay for me too! Thank you for your hard work!
